name: Publish coc-java

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test:
    name: Test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21', '23' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Build
        run: ./gradlew :coc-java:clean :coc-java:build --no-daemon --stacktrace

  publish:
    name: Publish to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (publish)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Extract version from tag
        id: version
        run: |
          REF="${GITHUB_REF#refs/tags/}"
          VERSION="${REF#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build
        run: ./gradlew :coc-java:clean :coc-java:build --no-daemon --stacktrace

      - name: Publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew -Pversion=${{ steps.version.outputs.version }} :coc-java:publish --no-daemon --stacktrace
