name: Publish Javadoc

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'coc-java/**'
      - '.github/workflows/publish-javadoc.yml'
      - 'build.gradle'
      - 'settings.gradle'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Javadoc
        run: ./gradlew --no-daemon :coc-java:javadoc

      - name: Publish to gh-pages/docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: coc-java/build/docs/javadoc
          destination_dir: docs
          enable_jekyll: false
